# Service1 Configuration
########################

server:
  port: 8002

spring:
  application:
    name: service2

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
    prefer-ip-address: true
    ip-address: 127.0.0.1
